// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHi70OW_QZvHK3pAVJIkJYyHq5t0BFMac',
    appId: '1:254846548296:ios:ba3ddab0a02e27be67db7d',
    messagingSenderId: '254846548296',
    projectId: 'chat-app-1251',
    storageBucket: 'chat-app-1251.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHi70OW_QZvHK3pAVJIkJYyHq5t0BFMac',
    appId: '1:254846548296:ios:ba3ddab0a02e27be67db7d',
    messagingSenderId: '254846548296',
    projectId: 'chat-app-1251',
    storageBucket: 'chat-app-1251.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJuEspsW7k_CVDcepHK349qW8dg-3NNs',
    appId: '1:254846548296:web:87a454a1e8698eb467db7d',
    messagingSenderId: '254846548296',
    projectId: 'chat-app-1251',
    authDomain: 'chat-app-1251.firebaseapp.com',
    storageBucket: 'chat-app-1251.firebasestorage.app',
    measurementId: 'G-QP3GLQJPK3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJuEspsW7k_CVDcepHK349qW8dg-3NNs',
    appId: '1:254846548296:web:87a454a1e8698eb467db7d',
    messagingSenderId: '254846548296',
    projectId: 'chat-app-1251',
    authDomain: 'chat-app-1251.firebaseapp.com',
    storageBucket: 'chat-app-1251.firebasestorage.app',
    measurementId: 'G-QP3GLQJPK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-ozBHRDs_K2icjjwZjeoMjaMI2dm0RY',
    appId: '1:254846548296:android:d9f854677e185dd167db7d',
    messagingSenderId: '254846548296',
    projectId: 'chat-app-1251',
    storageBucket: 'chat-app-1251.firebasestorage.app',
  );

}